### ISSUE TITLE
TypeScript环境，npm安装构建完毕后，报错“../rfdc" is not defined”。

### ISSUE THREAD

**Issue by xxvk** [wechat-miniprogram/computed#30]
module "miniprogram_npm/miniprogram-computed/rfdc" is not defined
Error: module "miniprogram_npm/miniprogram-computed/rfdc" is not defined
    at require (http://127.0.0.1:15699/appservice/__dev__/WAService.js:2:1609633)
    at http://127.0.0.1:15699/appservice/__dev__/WAService.js:2:1609384
    at Object.<anonymous> (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:552:20)
    at __webpack_require__ (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:61:23)
    at Object.<anonymous> (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:283:19)
    at __webpack_require__ (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:61:23)
    at Object.<anonymous> (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:268:20)
    at __webpack_require__ (http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:61:23)
    at http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:255:10
    at http://127.0.0.1:15699/appservice/miniprogram_npm/miniprogram-computed/index.js:257:2

**Comment by LastLeaf** [comment]
是使用了哪个代码片段吗？

**Comment by haxuhaibing** [comment]
原生小程序构建后也是😓
## 小程序版本v1.02.1911180
`  
"miniprogram-computed": "^2.1.1"
`
`thirdScriptError
module "miniprogram_npm/miniprogram-computed/rfdc" is not defined
Error: module "miniprogram_npm/miniprogram-computed/rfdc" is not defined
    at require (http://127.0.0.1:62980/appservice/__dev__/WAService.js:2:1671596)
    at http://127.0.0.1:62980/appservice/__dev__/WAService.js:2:1671347
    at Object.<anonymous> (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:378:20)
    at __webpack_require__ (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:27:31)
    at Object.<anonymous> (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:132:19)
    at __webpack_require__ (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:27:31)
    at Object.<anonymous> (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:117:20)
    at __webpack_require__ (http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:27:31)
    at http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:107:18
    at http://127.0.0.1:62980/appservice/miniprogram_npm/miniprogram-computed/index.js:109:2`

**Comment by LastLeaf** [comment]
rfdc 是 computed 的一个依赖库。报这个错误应该是因为依赖库没装上。

能不能说下具体是怎么出现的？

**Comment by songocean** [comment]
同 TypeScript 环境
### 解决方案

```cmd
npm install fast-deep-equal --save
npm install rfdc --save
```
猜测是微信开发者工具的 `构建 npm` 命令没有安装内部依赖

**Comment by LastLeaf** [comment]
`构建 npm` 并不会自动安装依赖哦

**Comment by TtTRz** [comment]
暂时关闭此 Issue，如有相关疑问，请提供可稳定复现问题的 DEMO（小程序代码片段）再重新打开此 Issue。
